language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"


install:
  - pip install coveralls
  - pip install coverage

script: "coverage run --source=pymp setup.py test"

after_success:
  - coveralls
